---
name: triton_example
channels:
  - conda-forge
  - nvidia
  - rapidsai
dependencies:
  - cudatoolkit=11.5
  - cuda-python<11.7.0
  - cudf=22.10
  - cuml=22.10
  - cupy
  - jupyter
  - kaggle
  - matplotlib
  - numpy
  - pandas
  - pip
  - python=3.8
  - scikit-learn
  - pip:
      - tritonclient[all]
      - protobuf==3.20.1
      - xgboost>=1.5,<1.6
