---
name: triton_example
channels:
  - conda-forge
  - nvidia
  - rapidsai
dependencies:
  - cuda-version=12.8
  - cudf=25.10
  - cuml=25.10
  - cupy
  - jupyter
  - kaggle
  - matplotlib
  - numpy
  - pandas
  - pip
  - python
  - rapidsai::xgboost>=3.0
  - scikit-learn>=1.5
  - pip:
      - tritonclient[all]
      - protobuf
