---
name: triton_faq_nb
channels:
  - conda-forge
  - nvidia
  - rapidsai
dependencies:
  - cudatoolkit=11.4
  - cuml=22.04
  - joblib
  - jupyter
  - lightgbm
  - numpy
  - pandas
  - pip
  - python=3.8
  - scikit-learn
  - skl2onnx
  - treelite=2.3.0
  - pip:
      - tritonclient[all]
      - xgboost>=1.5,<1.6
      - protobuf==3.20.1
