name: triton_test
channels:
  - conda-forge
  - nvidia
  - rapidsai
dependencies:
  - clang-tools=8.0.1
  - cudatoolkit=11.0
  - cuml=21.10
  - flake8
  - lightgbm
  - pip
  - python=3.8
  - rapidsai::py-xgboost
  - scikit-learn
  - pip:
      - tritonclient[all]
